### ISSUE TITLE
ImportError: cannot import name ToxAV

### ISSUE THREAD

**Issue by ymkim92** [aitjcize/PyTox#38]
Hello,

I installed PyTox on both my ubuntu trusty and docker, but both have the same problem.
When I run `python example/echo.py`, I meet this error:

```
root@db3d34e64d04:/PyTox# python examples/echo.py 
Traceback (most recent call last):
  File "examples/echo.py", line 26, in <module>
    from pytox import Tox, ToxAV
ImportError: cannot import name ToxAV
```

Can you help me?

Regards,
Kim

**Comment by aitjcize** [comment]
Sorry I've been busy. Can you show me the output of `python setup.py build`?

**Comment by ymkim92** [comment]
Hi  aitjcize,

This is the output

'''
$ python setup.py build
running build
running build_ext
building 'pytox' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pytox
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c pytox/pytox.c -o build/temp.linux-x86_64-2.7/pytox/pytox.o -Wall -Wno-declaration-after-statement -DENABLE_AV
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c pytox/core.c -o build/temp.linux-x86_64-2.7/pytox/core.o -Wall -Wno-declaration-after-statement -DENABLE_AV
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c pytox/util.c -o build/temp.linux-x86_64-2.7/pytox/util.o -Wall -Wno-declaration-after-statement -DENABLE_AV
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c pytox/av.c -o build/temp.linux-x86_64-2.7/pytox/av.o -Wall -Wno-declaration-after-statement -DENABLE_AV
creating build/lib.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/pytox/pytox.o build/temp.linux-x86_64-2.7/pytox/core.o build/temp.linux-x86_64-2.7/pytox/util.o build/temp.linux-x86_64-2.7/pytox/av.o -ltoxcore -ltoxav -o build/lib.linux-x86_64-2.7/pytox.so
$
'''

**Comment by aitjcize** [comment]
From the output the AV module is built. So you should able to import ToxAV. Can you try importing again? To make sure you are importing the correct module, please `cd build/lib.linux-x86_64-2.7` then `import Tox, ToxAV`

**Comment by ymkim92** [comment]
It is working! 

```
PyTox/build/lib.linux-x86_64-2.7$ python -c 'from pytox import Tox, ToxAV'
PyTox/build/lib.linux-x86_64-2.7$
```

But in examples foler:

```
PyTox/examples$ python -c 'from pytox import Tox, ToxAV'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name ToxAV
```

What can I do next? Thanks a lot!

**Comment by mrshu** [comment]
@ymkim92 if you are still interested you can try the current master, it uses the new tox API.
