### ISSUE TITLE
install failed via pip

### ISSUE THREAD

**Issue by randoms** [aitjcize/PyTox#47]
pip install pytox failed on windows.
details

    cl : Command line error D8021 : invalid numeric argument '/Wno-declaration-after-statement'
    error: command 'C:\\Users\\newne_000\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

It seems you setted the wrong compile flag for the cl.

**Comment by Adman** [comment]
@randoms I've got the same problem on Ubuntu

```
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by quininer** [comment]
you can try `pip install git+https://github.com/kitech/PyTox.git@newapi_tests`.

**Comment by Adman** [comment]
@quininer since this repository is broken, shouldn't be branch newapi_tests be merged into this repo's master?
cc @aitjcize

**Comment by kitech** [comment]
@Adman just use newapi branch is fine,   https://github.com/kitech/PyTox.git@newapi

**Comment by Adman** [comment]
@kitech both examples are broken. After I send friend requests it accepts me and throws AttributeError
```
Accepted.
Traceback (most recent call last):
  File "phone.py", line 321, in <module>
    t.loop()
  File "phone.py", line 288, in loop
    self.iterate()
AttributeError: on_friend_connection_status
```

**Comment by kitech** [comment]
try again please.  should be fixed now.

**Comment by kitech** [comment]
newapi has merge. 
but need change version and create a new pip package.

**Comment by mrshu** [comment]
@aitjcize could you bump the version and upload it to PyPI as @kitech suggests? I do not think anyone else has the rights to do that.
